/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { TimeLock, TimeLockInterface } from "../TimeLock";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "balances",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "getBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_secondsToIncrease",
        type: "uint256",
      },
    ],
    name: "increaseLockTime",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "lockTime",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610329806100206000396000f3fe6080604052600436106100555760003560e01c806312065fe01461005a57806327e235e3146100815780633ccfd60b146100b457806379af55e4146100cb578063a4beda63146100f5578063d0e30db014610128575b600080fd5b34801561006657600080fd5b5061006f610130565b60408051918252519081900360200190f35b34801561008d57600080fd5b5061006f600480360360208110156100a457600080fd5b50356001600160a01b0316610134565b3480156100c057600080fd5b506100c9610146565b005b3480156100d757600080fd5b506100c9600480360360208110156100ee57600080fd5b50356102a2565b34801561010157600080fd5b5061006f6004803603602081101561011857600080fd5b50356001600160a01b03166102ba565b6100c96102cc565b4790565b60006020819052908152604090205481565b3360009081526020819052604090205461019c576040805162461bcd60e51b8152602060048201526012602482015271496e73756666696369656e742066756e647360701b604482015290519081900360640190fd5b3360009081526001602052604090205442116101f7576040805162461bcd60e51b8152602060048201526015602482015274131bd8dac81d1a5b59481b9bdd08195e1c1a5c9959605a1b604482015290519081900360640190fd5b33600081815260208190526040808220805490839055905190929083908381818185875af1925050503d806000811461024c576040519150601f19603f3d011682016040523d82523d6000602084013e610251565b606091505b505090508061029e576040805162461bcd60e51b81526020600482015260146024820152732330b4b632b2103a379039b2b7321022ba3432b960611b604482015290519081900360640190fd5b5050565b33600090815260016020526040902080549091019055565b60016020526000908152604090205481565b336000908152602081815260408083208054340190556001909152902062093a804201905556fea264697066735822122059ae193be7ea8989c8149f4e860606d356f594496b07561c112285788f28a38d64736f6c63430007060033";

type TimeLockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TimeLockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TimeLock__factory extends ContractFactory {
  constructor(...args: TimeLockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "TimeLock";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<TimeLock> {
    return super.deploy(overrides || {}) as Promise<TimeLock>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): TimeLock {
    return super.attach(address) as TimeLock;
  }
  connect(signer: Signer): TimeLock__factory {
    return super.connect(signer) as TimeLock__factory;
  }
  static readonly contractName: "TimeLock";
  public readonly contractName: "TimeLock";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TimeLockInterface {
    return new utils.Interface(_abi) as TimeLockInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TimeLock {
    return new Contract(address, _abi, signerOrProvider) as TimeLock;
  }
}
