/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface TokenSenderInterface extends utils.Interface {
  contractName: "TokenSender";
  functions: {
    "getHash(address,uint256,address,address,uint256)": FunctionFragment;
    "transfer(address,uint256,address,address,uint256,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getHash",
    values: [string, BigNumberish, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [string, BigNumberish, string, string, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getHash", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;

  events: {};
}

export interface TokenSender extends BaseContract {
  contractName: "TokenSender";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TokenSenderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getHash(
      sender: string,
      amount: BigNumberish,
      recipient: string,
      tokenContract: string,
      nonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    transfer(
      sender: string,
      amount: BigNumberish,
      recipient: string,
      tokenContract: string,
      nonce: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getHash(
    sender: string,
    amount: BigNumberish,
    recipient: string,
    tokenContract: string,
    nonce: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  transfer(
    sender: string,
    amount: BigNumberish,
    recipient: string,
    tokenContract: string,
    nonce: BigNumberish,
    signature: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getHash(
      sender: string,
      amount: BigNumberish,
      recipient: string,
      tokenContract: string,
      nonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    transfer(
      sender: string,
      amount: BigNumberish,
      recipient: string,
      tokenContract: string,
      nonce: BigNumberish,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getHash(
      sender: string,
      amount: BigNumberish,
      recipient: string,
      tokenContract: string,
      nonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transfer(
      sender: string,
      amount: BigNumberish,
      recipient: string,
      tokenContract: string,
      nonce: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getHash(
      sender: string,
      amount: BigNumberish,
      recipient: string,
      tokenContract: string,
      nonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transfer(
      sender: string,
      amount: BigNumberish,
      recipient: string,
      tokenContract: string,
      nonce: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
